### ISSUE TITLE
Travis

### ISSUE THREAD

**Issue by kacperduras** [gabixdev/NekoooGuilds#2]
Może integracja repozytorium z https://travis-ci.org? Ja mam tak u siebie:
```
language: java
jdk:
- oraclejdk8
```

Pomaga to wstępnie testować kod, przed przyjęciem PR. Więcej musisz sobie poczytać w linku wyżej.

**Comment by gabixdev** [comment]
Planowałem użycie Jenkinsa, ale w sumie czemu nie skorzystać z tego?

**Comment by gabixdev** [comment]
Fixed.
